id: scheduled_extract_gdelt_data
namespace: newslakehouse
description: |
  The flow to schedule extraction of files into GCS bucket from data source GDELT URL "http://data.gdeltproject.org/gdeltv2/"

inputs:
  - id: filetype
    type: SELECT
    displayName: Select file type
    values: [export, mentions]
    defaults: export


variables:
  file: "{{trigger.date | date('yyyyMMddHHmmss')}}.{{inputs.filetype}}.CSV"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"
  data: "{{outputs.extract.outputFiles[(trigger.date | date('yyyyMMddHHmmss')) ~ '.' ~ inputs.filetype ~ '.CSV']}}" # Hardcoded for midnight only 

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      filetype: "{{inputs.filetype}}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.CSV"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO {{render(vars.file)}}.zip http://data.gdeltproject.org/gdeltv2/{{render(vars.file)}}.zip && unzip -o {{render(vars.file)}}.zip && rm {{render(vars.file)}}.zip


  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    projectId: "{{kv('GCP_PROJECT_ID')}}"
    serviceAccount: "{{kv('GCP_CREDS')}}"
    from: "{{render(vars.data)}}"
    to: "{{render(vars.gcs_file)}}"


pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      #serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: export_files_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * 1 * *" # Every 15mins on 1st day of every month
    inputs:
      filetype: export

  - id: mentions_files_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * 1 * *" # Every 15mins on 1st day of every month
    inputs:
      filetype: mentions