{{
    config(
        materialized='table'
    )
}}

with
    export_newsdata as (select * from {{ ref("stg_export_newsdata") }}),
    event_lookup as (select * from {{ ref("event_codes_lookup") }})
    select 
        GLOBALEVENTID,
        Event_Date,
        MonthYear,
        Event_Year,
        FractionDate,
        Actor1Code,
        Actor1Name,
        Actor1CountryCode,
        Actor1KnownGroupCode,
        Actor1EthnicCode,
        Actor1Religion1Code,
        Actor1Religion2Code,
        Actor1Type1Code,
        Actor1Type2Code,
        Actor1Type3Code,
        Actor2Code,
        Actor2Name,
        Actor2CountryCode,
        Actor2KnownGroupCode,
        Actor2EthnicCode,
        Actor2Religion1Code,
        Actor2Religion2Code,
        Actor2Type1Code,
        Actor2Type2Code,
        Actor2Type3Code,
        IsRootEvent,
        export_newsdata.EventCode as EventCode,
        EventCode_lookup.EventDescription as EventCode_type,
        EventBaseCode,
        export_newsdata.EventRootCode as EventRootCode,
        EventRootCode_lookup.EventDescription as EventRootCode_type,
        QuadClass,
        GoldsteinScale,
        NumMentions,
        NumSources,
        NumArticles,
        AvgTone,
        Actor1Geo_Type,
        Actor1Geo_FullName,
        Actor1Geo_CountryCode,
        Actor1Geo_ADM1Code,
        Actor1Geo_ADM2Code,
        Actor1Geo_Lat,
        Actor1Geo_Long,
        Actor1Geo_FeatureID,
        Actor2Geo_Type,
        Actor2Geo_FullName,
        Actor2Geo_CountryCode,
        Actor2Geo_ADM1Code,
        Actor2Geo_ADM2Code,
        Actor2Geo_Lat,
        Actor2Geo_Long,
        Actor2Geo_FeatureID,
        ActionGeo_Type,
        ActionGeo_FullName,
        ActionGeo_CountryCode,
        ActionGeo_ADM1Code,
        ActionGeo_ADM2Code,
        ActionGeo_Lat,
        ActionGeo_Long,
        ActionGeo_FeatureID,
        Event_Timestamp,
        SOURCEURL,
        Source_Domain,
        Coalesce(Actor1CountryCode, Actor2CountryCode, Actor1Geo_CountryCode, Actor2Geo_CountryCode, ActionGeo_CountryCode, Actor1Geo_FullName, Actor2Geo_FullName, Actor1Geo_ADM1Code, Actor1Geo_ADM2Code, Actor2Geo_ADM1Code, Actor2Geo_ADM2Code, ActionGeo_ADM1Code, ActionGeo_ADM2Code, ActionGeo_FullName) as CountryCode
    from export_newsdata 
    inner join event_lookup as EventCode_lookup
    on export_newsdata.EventCode = EventCode_lookup.EventCode
    inner join event_lookup as EventRootCode_lookup
    on export_newsdata.EventRootCode = EventRootCode_lookup.EventCode